"""try

Revision ID: 37e96262c433
Revises: a81f041b57fb
Create Date: 2022-01-23 14:56:57.724101

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "37e96262c433"
down_revision = "a81f041b57fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
