"""Added required tables

Revision ID: 7ac9a20e1e38
Revises: b6ce96680ed1
Create Date: 2022-01-24 21:19:55.308251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac9a20e1e38'
down_revision = 'b6ce96680ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
