"""Added required tables

Revision ID: 95f829f5a942
Revises: 7ac9a20e1e38
Create Date: 2022-01-24 21:20:54.629667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f829f5a942'
down_revision = '7ac9a20e1e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
