"""Add column

Revision ID: a0110508248c
Revises: c95c5b1eb339
Create Date: 2022-01-23 15:40:03.325958

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0110508248c"
down_revision = "c95c5b1eb339"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
