"""Change users

Revision ID: a81f041b57fb
Revises: f146144c20df
Create Date: 2022-01-23 14:55:23.679749

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a81f041b57fb"
down_revision = "f146144c20df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
