"""Add column

Revision ID: c95c5b1eb339
Revises: 37e96262c433
Create Date: 2022-01-23 15:39:36.242835

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c95c5b1eb339"
down_revision = "37e96262c433"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_name")
    # ### end Alembic commands ###
