"""Change users

Revision ID: f146144c20df
Revises: adf21febe44b
Create Date: 2022-01-23 14:49:58.681270

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f146144c20df"
down_revision = "adf21febe44b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
